apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ui
  template:
    metadata:
      labels:
        app: backend-ui
    spec:
      containers:
      - name: backend-ui
        image: ghcr.io/zpp-quantumai/backend-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: mongodb
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: test
        - name: SPRING_DATA_MONGODB_USERNAME
          value: test
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: test
        - name: SPRING_KAFKA_BOOTSTRAPSERVERS
          value: localhost:9092,kafka-service:9092

---

apiVersion: v1
kind: Service
metadata:
  name: backend-ui
spec:
  selector:
    app: backend-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer