apiVersion: v1
kind: Service
metadata:
  name: backend-ui
spec:
  type: LoadBalancer
  loadBalancerIP: 34.118.116.44 # Replace with your reserved IP address.
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend-ui