apiVersion: apps/v1
kind: Deployment
metadata:
  name: utm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utm
  template:
    metadata:
      labels:
        app: utm
    spec:
      containers:
        - name: utm
          image: ghcr.io/zpp-quantumai/utm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              value: test
            - name: MONGO_PASSWORD
              value: test
---

apiVersion: v1
kind: Service
metadata:
  name: utm
spec:
  selector:
    app: umt
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080