name: Docker-build

on:
  push:
    branches:
      - main
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test.
        with:
          repository: ZPP-QuantumAI/DevOps
          ref: main
        run: ./build.sh $GITHUB_REPOSITORY