on:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'deploy'
    steps:
      - name: Test
        env:
          TEST: ${{ secrets.TEST }}
        run: |
          echo $TEST
        shell: bash
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
