on:
  workflow_call:
jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: 'docker build'
    steps:
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - run: |
          wget https://raw.githubusercontent.com/ZPP-QuantumAI/DevOps/main/scripts/build.sh
          chmod +x build.sh
          ./build.sh ${{ github.event.repository.name }}
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add next-version.txt
          git commit -m "Change next-version.txt"
          git push
        shell: bash

      - name: Authenticate Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure kubectl
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials zpp-cluster --region europe-central2 --project zpp-cluster

      - name: Deploy
        run: |
          deployment_name=${{ github.event.repository.name }}
          replicas=$(kubectl get deployment $deployment_name -o=jsonpath='{.spec.replicas}')
          echo "current number of replicas: $replicas"
          kubectl scale deployment $deployment_name --replicas=0
          kubectl scale deployment $deployment_name --replicas=$replicas
