on:
  workflow_call:
jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: 'docker build'
    steps:
      - uses: ZPP-QuantumAI/DevOps/actions/build@main
        with:
          docker_key: ${{ secrets.DOCKER_KEY }}