on:
  workflow_call:
jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: 'docker build'
    steps:
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: "mmaciek87"
          password: "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"
      - uses: actions/checkout@v3
      - run: |
          wget https://raw.githubusercontent.com/ZPP-QuantumAI/DevOps/main/build.sh
          chmod +x build.sh
          ./build.sh ${{ github.event.repository.name }}
        shell: bash