on:
  workflow_call:
jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: 'docker build'
    steps:
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - run: |
          wget https://raw.githubusercontent.com/ZPP-QuantumAI/DevOps/main/build.sh
          chmod +x build.sh
          ./build.sh ${{ github.event.repository.name }}
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add new-version.txt
          git commit -m "Change new-version.txt"
          git push
        shell: bash